"use client";

import Image from "next/image";
import { Check, X } from "lucide-react";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";

type DemoState = { loggedIn: boolean; followed: string[]; liked: string[]; bookmarked: string[]; };
type CommunityContextValue = DemoState & { requestLogin: (afterLogin?: () => void) => void; logout: () => void; toggleFollow: (id: string) => void; toggleLike: (id: string) => void; toggleBookmark: (id: string) => void; notify: (message: string) => void; };
const initialState: DemoState = { loggedIn: false, followed: [], liked: [], bookmarked: [] };
const storageKey = "wuthering-demo-community-v1";
const CommunityContext = createContext<CommunityContextValue | null>(null);
function toggle(items: string[], id: string) { return items.includes(id) ? items.filter((item) => item !== id) : [...items, id]; }

export function CommunityDemoProvider({ children }: { children: ReactNode }) {
  const [state, setState] = useState<DemoState>(initialState); const [hydrated, setHydrated] = useState(false); const [loginOpen, setLoginOpen] = useState(false); const [pendingAction, setPendingAction] = useState<(() => void) | null>(null); const [toast, setToast] = useState("");
  const [phone, setPhone] = useState(""); const [verification, setVerification] = useState(""); const [agreement, setAgreement] = useState(false); const [codeSent, setCodeSent] = useState(false); const [formError, setFormError] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = window.localStorage.getItem(storageKey); if (saved) setState({ ...initialState, ...JSON.parse(saved) }); } catch { /* Keep the Demo usable when storage is unavailable. */ } setHydrated(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (hydrated) window.localStorage.setItem(storageKey, JSON.stringify(state)); }, [hydrated, state]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 2600); return () => window.clearTimeout(timer); }, [toast]);
  const requireLogin = useCallback((action?: () => void) => { if (state.loggedIn) { action?.(); return; } setPendingAction(() => action ?? null); setLoginOpen(true); }, [state.loggedIn]);
  const value = useMemo<CommunityContextValue>(() => ({ ...state, requestLogin: requireLogin, logout: () => { setState((current) => ({ ...current, loggedIn: false })); setToast("已退出 Demo 登录状态"); }, toggleFollow: (id) => requireLogin(() => setState((current) => ({ ...current, followed: toggle(current.followed, id) }))), toggleLike: (id) => requireLogin(() => setState((current) => ({ ...current, liked: toggle(current.liked, id) }))), toggleBookmark: (id) => requireLogin(() => setState((current) => ({ ...current, bookmarked: toggle(current.bookmarked, id) }))), notify: setToast }), [requireLogin, state]);
  function closeLogin() { setLoginOpen(false); setFormError(""); }
  function sendCode() { if (!/^1\d{10}$/.test(phone)) { setFormError("请输入正确的 11 位手机号"); return; } setCodeSent(true); setFormError(""); setToast("验证码已发送至 " + phone.slice(0, 3) + "****" + phone.slice(-4)); }
  function login(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!/^1\d{10}$/.test(phone)) { setFormError("请输入正确的 11 位手机号"); return; } if (!/^\d{6}$/.test(verification)) { setFormError("请输入 6 位验证码"); return; } if (!agreement) { setFormError("请先阅读并同意用户协议与隐私政策"); return; } setState((current) => ({ ...current, loggedIn: true })); setLoginOpen(false); setToast("已登录鸣潮社区"); pendingAction?.(); setPendingAction(null); }
  return <CommunityContext.Provider value={value}>{children}{toast && <div className="community-toast" role="status"><Check size={15} />{toast}</div>}{loginOpen && <div className="dialog-backdrop login-backdrop" onClick={closeLogin} role="presentation"><section className="login-dialog login-dialog--phone" aria-modal="true" aria-label="登录鸣潮社区" role="dialog" onClick={(event) => event.stopPropagation()}><button className="dialog-close" onClick={closeLogin} type="button" aria-label="关闭登录"><X size={28} strokeWidth={2.1} /></button><div className="login-hero"><div className="login-title"><span>欢迎登录</span><strong>鸣潮社区</strong><small>WUTHERING WAVES COMMUNITY</small></div><Image alt="鸣潮社区潮汐终端" className="login-mascot" height={230} priority src="/art/login-tide-terminal.png" width={230} /></div><form className="phone-login-form" onSubmit={login}><label className="phone-field"><span>+86</span><input autoComplete="tel" inputMode="numeric" maxLength={11} onChange={(event) => setPhone(event.target.value.replace(/\D/g, ""))} placeholder="请输入手机号码" type="tel" value={phone} /></label><label className="code-field"><input inputMode="numeric" maxLength={6} onChange={(event) => setVerification(event.target.value.replace(/\D/g, ""))} placeholder="请输入 6 位验证码" value={verification} /><button onClick={sendCode} type="button">{codeSent ? "已发送" : "获取验证码"}</button></label>{formError && <p className="login-form-error" role="alert">{formError}</p>}<button className="phone-login-submit" type="submit">登录</button><label className="agreement-field"><input checked={agreement} onChange={(event) => setAgreement(event.target.checked)} type="checkbox" /><span>我已阅读并同意 <a href="#agreement">《用户协议》</a>、<a href="#privacy">《隐私政策》</a>，未注册手机号验证成功后将自动注册。</span></label></form></section></div>}</CommunityContext.Provider>;
}
export function useCommunityDemo() { const context = useContext(CommunityContext); if (!context) throw new Error("useCommunityDemo must be used inside CommunityDemoProvider"); return context; }
